[package]
name = "libreauth"
version = "0.6.1"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
description = "Collection of tools for user authentication."
keywords = ["authentication", "password", "oath", "hotp", "totp"]
documentation = "https://docs.rs/libreauth/"
repository = "https://github.com/breard-r/libreauth"
readme = "README.md"
license = "CECILL-2.1"
include = ["src/**/*", "Cargo.toml", "LICENSE-*.txt"]

[package.metadata.docs.rs]
features = ["cbindings"]

[lib]
name = "libreauth"
crate-type = ["rlib", "dylib"]

[features]
cbindings = ["libc"]

[dependencies]
rust-argon2 = "^0.3.0"
pbkdf2 = "^0.1.0"
hmac = "^0.4"
sha-1 = "^0.4"
sha2 = "^0.6"

base64 = "^0.9.0"
base32 = "^0.3.0"
rand = "^0.3.14"
time = "^0.1.31"
hex = "^0.3.1"
nom = "^2.2.1"

[dependencies.libc]
version = "^0.1.8"
optional = true
