[package]
name = "libreauth"
version = "0.5.2"
authors = ["Rodolphe Breard <rodolphe@what.tf>"]
description = "Collection of tools for user authentication."
documentation = "https://what.tf/libreauth/"
repository = "https://github.com/breard-r/libreauth"
readme = "README.md"
keywords = ["authentication", "2fa", "otp", "hotp", "totp"]
license = "CECILL-2.1"
include = ["src/**/*", "Cargo.toml", "LICENSE.txt"]

[lib]
name = "libreauth"
crate-type = ["rlib", "dylib"]

[features]
cbindings = ["libc"]

[dependencies]
rust-crypto = "^0.2.31"
base32 = "^0.3.0"
rand = "^0.3.14"
time = "^0.1.31"
nom = "^2.2.1"

[dependencies.libc]
version = "^0.1.8"
optional = true
